version: '3.2'

services:
  nginx:
    container_name: oat-nginx
    image: nginx:stable
    ports:
      - "8000:80"
    volumes:
      - ./:/www/oat-api
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    container_name: oat-php
    build:
      context: ./docker/php
    volumes:
      - ./:/www/oat-api
    working_dir: /www/oat-api