version: '3.2'

services:
  nginx:
    container_name: oat-nginx
    image: nginx:stable
    ports:
      - "8000:80"
    volumes:
      - ./:/www/oat-api
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    container_name: oat-php-fpm
    build:
      context: ./docker/php
    volumes:
      - ./:/www/oat-api
    working_dir: /www/oat-api

  swagger-ui:
    container_name: oat-swagger-ui
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./open-api.yml:/open-api.yml
    environment:
      SWAGGER_JSON: /open-api.yml